### ISSUE TITLE
TRAVIC tram/bus data

### ISSUE THREAD

**Issue by mehdisadeghi** [n7a235/README#14]
I am opening this issue here, because I'm not sure whether we are going to keep the DB repo.

Apparently TRAVIC uses [open data from googletransitdatafeed - PublicFeeds.wiki](https://code.google.com/archive/p/googletransitdatafeed/wikis/PublicFeeds.wiki) published by transport agencies. The realtime visulization on their is actually off-line. Here is the quote appearing when you click on a bus or tram:
> Vehicle position based on interpolated schedule data

and About TRAVIC page:
> This tracker provides movement visualization of transit data published by transit agencies and operators from all over the world. The movements are mostly based on static schedule data. Wherever real-time data is available it is also included in the visualization.

They state the source of this to be DB. So the question is how they have extracted this info. I can't find it among DB data yet.

**Comment by mehdisadeghi** [comment]
There are a couple of datasets In [this link](https://navitia.opendatasoft.com/explore/dataset/de/table/?sort=type_file) which cover the transport data for Berlin, Mannheim, Ulm, Cologne and Aachen.

**Comment by carocad** [comment]
@mehdisadeghi based on your input I would say that our best option is to create/use a DB crawler to get information through their API. Since TRAVIC doesnt expose that information I guess it is either not-public or gotten through unofficial methods. We cannot rely on GTFS files being available for most German cities, we need another input source.

**Comment by carocad** [comment]
extract from email. For privacy and respect reason I dont paste the full content here
```
Hey Camo,

So my guess was correct, the DB feed is private and not publicly available. See the email below.

Regards,
Mehdi
.
.
.
```

Well this was somehow expected. It would probably be the case for us once we have a reliable product. For the time being we have to use what we have at hand. See my answer on #7. It might be worth contacting the transport agencies directly and asking them for the data. Nevertheless I think we should focus on the initial task. Getting a prototype that we can use.

**Comment by mehdisadeghi** [comment]
> It might be worth contacting the transport agencies directly and asking them for the data

Deutsche Bahn has a contact person for open data, I'll ask them. They are probably open to give access to the data for non-commercial use.

**Comment by carocad** [comment]
@mehdisadeghi any answer from them?

**Comment by mehdisadeghi** [comment]
No. I'll update this issue when I get a reply. BTW, we could have joined their [Hackaton](https://www.europeandataportal.eu/en/news/open-data-hackathon-deutsche-bahn) which was in May and probably meet their developers.

**Comment by carocad** [comment]
oh shit. We missed it. Well next time we will join with an even greater app and service :)

**Comment by mehdisadeghi** [comment]
> Auf https://dbmindbox.com/de/db-opendata-hackathons/hackathons/contest-2017 haben wir aufgelistet, welche aktuell bekannt sind: Am weitesten geht im Moment das Angebot des VBB.
Berlin-Brandenburg: Über den Verkehrsverbund Berlin-Brandenburg gibt es eine API für Echtzeitdaten zu allen S-Bahnen, U-Bahnen, Bussen, Trams in Berlin-Brandenburg + Fahrpläne als GTFS www.vbb.de/de/article/fahrplan/webservices/schnittstellen-fuer-webentwickler/5070.html
Ulm: www.swu.de/privatkunden/service/mobilitaet/gtfs-daten/
VRS: www.vrsinfo.de/fahrplan/oepnv-daten-fuer-webentwickler.html
RNV: opendata.rnv-online.de
AVV: opendata.avv.de
VAG: opendata.vag.de

Above is the answer from DB team. Have a look.

**Comment by mehdisadeghi** [comment]
BTW, the first link says the competition is ongoing.

**Comment by carocad** [comment]
@mehdisadeghi Great !! Nice to know about this. After checking the links, it got me thinking: would it be better to first release our app in a place with no open information such that we show our capabilities, or rather in a place with full open information such that we can leverage it? 
- the first option would mean lots of work but I guess we are more likely to find people to test it in our own towns (which might not have open information)
- the second option would give us knowledge really quick and boost the functionality but we would be left with no one to use it since we dont know anybody there.

Just some thoughts on the topic ;)

BTW: I just checked the first link. Although it sounds interesting, after I checked the previous winners it didnt stroke me as much. Mostly sketchy ideas of how it could be. Plus the prices are quite small.

I think that if we would submit ourselves to that deadline and to have a full alpha release it would be too much.

I am closing this as it is clear now from where can we get the some of the information that we want. The rest is (I think) implementation details. 

Feel free to re-open it if you think we need to discuss this more
